name: X86_64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check_update:
    name: Check update
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
      - uses: actions/checkout@v4
      - name: Check version
        id: check_version
        run: |
          apt update
          apt build-dep . -y
          dpkg-buildpackage -b -us -uc -d
